### ISSUE TITLE
Default python version may not be 2

### ISSUE THREAD

**Issue by abooij** [JasonGross/coq-tools#36]
```
$ python find-bug.py -h 
Traceback (most recent call last):
  File "find-bug.py", line 1045, in <module>
    args = process_logging_arguments(parser.parse_args())
  File "/home/auke/dev/coq-tools/argparse.py", line 1688, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/home/auke/dev/coq-tools/argparse.py", line 1709, in parse_known_args
    if isinstance(action.default, basestring):
NameError: name 'basestring' is not defined
```
```
$ python2 find-bug.py -h
usage: find-bug.py [-h] [--fast-merge-imports] [--no-wrap-modules]
                   [--absolutize-constants] [--strip-newlines [N]]
                   [--no-admit-opaque] [--no-admit-transparent]
                   [--no-aggressive] [--no-remove-typeclasses]
                   [--dynamic-header [DYNAMIC_HEADER]] [--header [HEADER]]
                   [--no-strip-trailing-space] [--no-deps]
...
```

This is on Arch Linux, where the default python version is 3. The instructions in the README should probably be modified, and the first line of the scripts should be modified to say:
```
#!/usr/bin/env python2
```

**Comment by JasonGross** [comment]
Thanks!
