### ISSUE TITLE
minimize-requires: conflicting option string --arg

### ISSUE THREAD

**Issue by anton-trunov** [JasonGross/coq-tools#37]
When I run `minimize-requires.py` I get the following error message:

```
$ ./minimize-requires.py
Traceback (most recent call last):
  File "./minimize-requires.py", line 44, in <module>
    add_libname_arguments(parser)
  File "/Users/anton/Dropbox/mathador/fcsl/coq-tools/custom_arguments.py", line 50, in add_libname_arguments
    help='Arguments to pass to coqc and coqtop; e.g., " -indices-matter" (leading and trailing spaces are stripped)')
  File "/Users/anton/Dropbox/mathador/fcsl/coq-tools/argparse.py", line 1295, in add_argument
    return self._add_action(action)
  File "/Users/anton/Dropbox/mathador/fcsl/coq-tools/argparse.py", line 1669, in _add_action
    self._optionals._add_action(action)
  File "/Users/anton/Dropbox/mathador/fcsl/coq-tools/argparse.py", line 1496, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "/Users/anton/Dropbox/mathador/fcsl/coq-tools/argparse.py", line 1309, in _add_action
    self._check_conflict(action)
  File "/Users/anton/Dropbox/mathador/fcsl/coq-tools/argparse.py", line 1447, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "/Users/anton/Dropbox/mathador/fcsl/coq-tools/argparse.py", line 1454, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument --arg: conflicting option string(s): --arg
```

I was able to successfully run the utility on our project after the following modification (I had to use python2 and renamed the conflicting option):
```
diff --git a/minimize-requires.py b/minimize-requires.py
index 464956a..9564291 100755
--- a/minimize-requires.py
+++ b/minimize-requires.py
@@ -1,4 +1,4 @@
-#!/usr/bin/env python
+#!/usr/bin/env python2
 import argparse, shutil, os, os.path, sys, re
 from custom_arguments import add_libname_arguments, update_env_with_libnames, add_logging_arguments, process_logging_arguments
 from split_file import get_coq_statement_ranges, UnsupportedCoqVersionError
@@ -39,7 +39,7 @@ parser.add_argument('--coqbin', metavar='COQBIN', dest='coqbin', type=str, defau
                     help='The path to a folder containing the coqc and coqtop programs.')
 parser.add_argument('--coqc', metavar='COQC', dest='coqc', type=str, default='coqc',
                     help='The path to the coqc program.')
-parser.add_argument('--arg', metavar='ARG', dest='coqc_args', type=str, action='append',
+parser.add_argument('--args', metavar='ARG', dest='coqc_args', type=str, action='append',
                     help='Arguments to pass to coqc; e.g., " -indices-matter" (leading and trailing spaces are stripped)')
 add_libname_arguments(parser)
 add_logging_arguments(parser)
```

I'm not submitting a PR because I have no idea if this is the right way to fix the issue.
Thank you for the tool!

**Comment by JasonGross** [comment]
Thanks!  Now fixed

**Comment by anton-trunov** [comment]
I tried deleting the duplicate conflicting option too, but it didn't work for me. Here is what I get with the most recent master:

```
$ coq-tools/minimize-requires.py -R . fcsl --arg "-w -notation-overridden,-local-declaration,-redundant-canonical-projection,-projection-no-head-constant" prelude.v
Traceback (most recent call last):
  File "coq-tools/minimize-requires.py", line 189, in <module>
    'coqc_args': (args.coqc_args if args.coqc_args else tuple()),
AttributeError: 'Namespace' object has no attribute 'coqc_args'

$ python2 --version
Python 2.7.14
```

**Comment by JasonGross** [comment]
Thanks, now fixed.  Crossing my fingers that there are no other bugs, but please do comment (here or in a new issue) if there are more.

**Comment by anton-trunov** [comment]
That was incredibly quick! It works now. Thanks a lot!
