### ISSUE TITLE
find-bug.py fails to process a list of warnings in _CoqProject file

### ISSUE THREAD

**Issue by anton-trunov** [JasonGross/coq-tools#38]
My `_CoqProject` file contains the following list of expected warnings:
```
-arg "-w -notation-overridden,-local-declaration,-redundant-canonical-projection,-projection-no-head-constant"
```

When I run `find-bug.py -f _CoqProject test.v bug.v` I get the following error message:

```
Traceback (most recent call last):
  File "/Users/antontrunov/prj/coq/coq-tools/find-bug.py", line 1132, in <module>
    update_env_with_libnames(env, args)
  File "/Users/antontrunov/prj/coq/coq-tools/custom_arguments.py", line 136, in update_env_with_libnames
    process_CoqProject(env, env['_CoqProject'])
  File "/Users/antontrunov/prj/coq/coq-tools/custom_arguments.py", line 116, in process_CoqProject
    append_coq_arg(env, tokens[i+1])
  File "/Users/antontrunov/prj/coq/coq-tools/custom_arguments.py", line 102, in append_coq_arg
    env[key] = tuple(list(env.get(key, [])) + list(argstring_to_iterable(arg)))
TypeError: 'NoneType' object is not iterable
```

**Comment by JasonGross** [comment]
Thanks!  Now fixed

**Comment by anton-trunov** [comment]
Works perfectly! Thank you.
